project:
  type: website

website:
  title: "À la baille"
  navbar:
    search: true
    right: 
      - glossaire.qmd
      - about.qmd
      - icon: rss
        href: index.xml
  page-footer:
    left: "© 2023 CC BY-NC-SA, Roch Delannay. Ce site a été réalisé avec [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/RochDLY/carnet-these
      - icon: twitter
        href: https://twitter.com/Roch_DLY
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  site-url: "https://cailloux.en-cours-de.construction"
format:
  html:
    title-block-banner: false
    theme:
      light: flatly
      dark: solar
    citation:
      language: fr
      type: post-weblog
    citations-hover: true
    footnotes-hover: true
    nocite: |
      @*
    csl: bibliographie/csl/apa.csl
    css: styles.css
    mainfont: Draftside Regular
    toc: true

# Informations sur l'auteur
author:
    name: Roch Delannay
    orcid: 0000-0002-3519-4365
    email: roch.delannay@gmail.com
    affiliations:
      - id: upn
        name: Université Paris Nanterre
        city: Paris
        state: France
      - id: udem
        name: Université de Montréal
        city: Montréal
        state: Québec



