project:
  type: website

website:
  title: "À la baille"
  navbar:
    search: true
    right: 
      - about.qmd
      - icon: rss
        href: index.xml
  page-footer:
    left: "© 2023 WTFPL, Roch Delannay. Ce site a été réalisé avec [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  site-url: "https://cailloux.en-cours-de.construction"
format:
  html:
    theme:
      light: litera
      dark: vapor
    css: styles.css
    toc: true



