---
title: "Carnet de recherche"
listing:
  contents: posts
  sort: "date desc"
  type: table
  fields: [title, date, categories]
  table-hover: true
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: false
---

Je suis Roch et ceci est mon carnet.  
Celui-ci se trouve à mi-chemin entre une écriture de recherche et une autre plus personnelle, intime.
Les billets relatent des réflexions qui me traversent, des mots qui me viennent à l'esprit au moment de me mettre derrière le clavier, ou encore de mes travaux de recherche.
Finalement, ce carnet n'appartient à aucune des deux catégories mentionnées mais plutôt à celle du journal de bord et de mes errances.  
Ce carnet au format web se nomme "à la baille", c'est là que j'y jette toutes mes pensées, et c'est à travers elles que de temps à autre je circule.
Certaines sont des détritus, des déchets sur lesquels je ne reviendrai jamais, alors que d'autres sont plus intéressantes et plus percutantes.
J'ouvre ce carnet à la lecture dans un espace "public", le Web, pour donner à voir la formation et la construction d'une pensée et d'un chercheur.
Pour montrer cette évolution, je n'éditerai pas les billets postés, sauf exception où la mention [Edit - Date] sera ajoutée à la fin du billet ainsi que le contenu additionnel, à la suite du billet initial.
