---
title: "Architexte"
date: "2023-02-28"
citation: false
---

**Jeanneret et Souchier, *Le Numérique comme écriture*, 2019 (voir le [Glossaire](https://www-cairn-info.faraway.parisnanterre.fr/le-numerique-comme-ecriture--9782200618582-page-301.htm))**

Gérard Genette avait défini l’architexte comme « l’ensemble des catégories générales, ou transcendantes – types de discours, modes d’énonciation, genres littéraires, etc. – dont relève chaque texte singulier ». Cherchant à ouvrir la voie à une « théorie générale des formes littéraires », il précisait alors que « l’objet de la poétique n’est pas le texte, mais l’architexte » (G. Genette, 1979).

Spécifiquement appliquée aux médias informatisés, la notion d’architexte que nous convoquons n’est pas extérieure au texte mais lui est constitutive et opératoire. Nous partons du constat qu’« on ne peut produire un texte à l’écran sans outils d’écriture situés en amont » (Y. Jeanneret, E. Souchier, 1999). Suivant une étymologie grecque (archè, origine et commandement), nous proposons le terme architexte pour désigner « les outils qui permettent l’existence de l’écrit à l’écran et qui, non contents de représenter la structure du texte, en commandent l’exécution et la réalisation ».

Initialement défini comme une « écriture d’écriture » puis comme un « dispositif d’écriture écrit », l’architexte s’avère être un point de passage obligé pour toute activité numérique. Il n’y a effectivement pas d’écriture à l’écran sans un architexte qui la rend possible, l’accompagne et la formate. Pour la première fois de son histoire, l’homme a donc recours à des « dispositifs d’écriture écrits » spécifiques pour pouvoir pratiquer une activité d’écriture (E. Souchier, 1998, 2013). Or, précisément en ce qu’ils sont « eux-mêmes écrits », les architextes « sont des textes lisibles et interprétables. Porteurs et prescripteurs d’une écriture à venir, ils anticipent de ce fait une figure de l’auteur » (É. Candel, G. Gomez Mejia, 2013) et relèvent donc de « l’énonciation éditoriale » (E. Souchier, 1998).

Les logiciels de traitement de texte ou les formulaires d’actualisation des pages Web, par exemple, sont des architextes qui balisent et régissent le montage des écritures à l’écran. Les architextes posent la question de la relation établie entre la technique et les langages symboliques dans la production des textes numériques. Mais ils sont également situés au cœur de la question cruciale des rapports de pouvoir tissés entre tous les partenaires de l’énonciation éditoriale (V. Jeanne-Perrier, 2006). Les architextes régulent effectivement la « polyphonie énonciative », de toutes les « voix » qui s’expriment sur les médias informatisés.


- Genette G., Introduction à l’architexte, Paris, Seuil, 1979.
- Souchier E., Lire et écrire : éditer ; des manuscrits aux écrans. Autour de l’œuvre de Raymond Queneau, Habilitation à diriger des recherches, Université Paris 7 Denis Diderot, 1998.
- Jeanneret Y., souchier e., « Pour une poétique de l’écrit d’écran », Xoana, n° 6, 1999.
- Souchier E., jeanneret y., le marec J. (sous la dir. de), Lire, écrire, récrire. Objets, signes et pratiques des médias informatisés, Paris, Bibliothèque Publique d’Information-Centre Pompidou, 2003.
- Jeanne-Perrier V., « Des outils d’écriture aux pouvoirs exorbitants ? », Réseaux, n° 137, 2006.
- Souchier E., « Le livre au risque de l’écrit d’écran et des écrits de réseaux », in A. Zali (dir.), La grande aventure du livre. De la tablette d’argile à la tablette numérique, Bibliothèque nationale de France-Hatier, 2013.
- Candel É., Gomez-Mejia G., « Écrire l’auteur. La pratique éditoriale comme construction socioculturelle de la littérarité des textes sur le Web », in S. Ducas et O. Deseilligny (dir.), L’auteur en réseau, les réseaux de l’auteur, Presses Universitaires de Paris Nanterre, 2013.
- Gomez-Mejia G., Les fabriques de soi ? Identité et industrie sur le Web, Paris, MkF éditions, 2016. 
