---
title: "Les quatre cadres de l'écrit d'écran"
date: "2023-04-05"
citation: false
---

Souchier, E., Candel, É. & Gomez-Mejia, G. (2019). Chapitre 1. Le numérique, c’est de l’écriture. Dans : , V. Jeanne-Perrier, *Le numérique comme écriture: Théories et méthodes d'analyse* (pp. 21-77). Paris: Armand Colin.

Une telle relation s’établit à travers quatre étapes essentielles symbolisées par quatre « cadres » distincts mais complémentaires qui vont disparaître au cours de l’usage. Prenons l’exemple d’un traitement de texte pour illustrer ce processus. Pour pouvoir écrire il me faut tout d’abord disposer d’un ordinateur composé en premier lieu par ce que l’on appelle ordinairement le « hardware », le matériel en somme. La traduction de l’expression anglaise renvoie du reste à de la quincaillerie, ce qui marque un écart sensible dans la perception que l’on se fait du dispositif d’une langue ou d’une culture à l’autre.

Ce cadre matériel – cet écran physique – est le premier espace dans lequel va s’inscrire l’activité dynamique de la machine. C’est toutefois le seul à être inerte. Il est comparable à la toile du peintre ou à l’écran du cinéaste ou bien encore à la page blanche du cahier d’écolier par exemple. On notera alors que le format des écrans des médias informatisés est héritier du monde audio-visuel. Il est en effet passé de la verticale dominant l’univers du livre à l’horizontale des formats paysage des écrans de cinéma et de télévision. L’industrie des écrans d’ordinateurs a emprunté ses modèles et ses modes de fabrication au registre télévisuel, transformant ainsi l’espace visuel et intellectuel de notre travail quotidien. Les fabricants de smartphones ont rapidement su jouer de la double direction en proposant pour nos usages nomades une fonction pour la rotation de l’écran.

Le deuxième espace se met en place au démarrage de l’ordinateur, il s’agit du cadre système. Le « système » est le logiciel qui va régir le fonctionnement de la machine elle-même et qui va rendre possibles les multiples activités potentiellement réalisables. Il nous permet de lui « faire faire » les tâches pour lesquelles il a été programmé. Sur ce cadre viennent s’afficher toutes les icônes activables (ou « signes passeurs » ; Souchier, Le Marec, Jeanneret, 2003 : 23) qui permettent de le faire fonctionner. Et s’il n’est pas dédié à la pratique d’écriture à proprement parler, il relève néanmoins des cadres logiciels dont il forme le premier niveau. Les systèmes d’exploitation, mais aussi certains logiciels indispensables au fonctionnement de la machine, le logiciel BIOS défini comme un « système élémentaire d'entrée/sortie » par exemple, relèvent du cadre système.

Une fois le système lancé et la machine activée, je dois requérir un autre logiciel consacré à l’activité que je veux mettre en œuvre. Pour écrire, je vais choisir un traitement de texte et ouvrir par là-même un autre « cadre » sur mon écran, une autre « fenêtre », celle du logiciel dédié à cette tâche. Je ne suis plus alors dans la logistique de la machine comme précédemment mais dans celle de mon activité. Le cadre logiciel en définit les limites et les possibilités. Pour le traitement de texte par exemple, il va afficher la « barre d’outils » et une « fenêtre » spécifique, un « document » vierge sur lequel je vais pouvoir commencer à écrire. Il ne s’agit là bien entendu que d’une coquille vide, quand bien même munie de multiples outils de travail, d’un dispositif et de son cadre d’opération.

Pour finir, je vais ouvrir un dernier cadre, celui du document, sur lequel je vais commencer à rédiger les lignes que vous êtes en train de lire. Autrement dit, mon activité d’écriture s’inscrit dans pas moins de quatre cadres sémiotiques distincts (figure 1.8). Le premier relève du matériel et les trois suivants de l’ingénierie textuelle informatique. Ce processus résumé de façon schématique est valable pour toute activité de travail ou de loisir réalisée sur un ordinateur (la notion de document renvoyant ici à tout type de tableau, projet, graphique, présentation, partie de jeu, vidéo, partition musicale, etc.).

Le premier « cadre » définit les conditions de possibilités matérielles de l’activité, c’est le seul inanimé. Les trois suivants, cadres système, logiciel et document, relèvent de l’ingénierie textuelle et définissent les conditions de réalisation de l’activité. On voit ainsi qu’une activité d’écriture réalisée sur le « document » d’un logiciel de traitement de texte est mise en abyme au sein de l’ensemble des autres « cadres » qui la rendent possible et la déterminent techniquement et sémiotiquement.

À cet enchâssement de cadres, il faudrait encore ajouter ceux que composent, à l’intérieur même du document, les rubriques, encadrés, cartouches, « boîtes de dialogue » ou autres formes de cadres éditoriaux structurants pour le travail même du texte : à ce niveau, la mise en abyme rejoint la forme plus générale et plus ancienne des multiples formes textuelles dont les médias informatisés, fruits d’une longue filiation, sont les héritiers.

On soulignera alors un paradoxe structurant des médias informatisés : les très grandes potentialités combinatoires offertes par les logiciels s’inscrivent nécessairement dans ces différents « cadres » qui instituent un rapport balisé extrêmement contraint au sein d’un même espace, celui de l’écran. La question est cruciale pour les téléphones portables et pour tous les dispositifs dont la surface est particulièrement contrainte : l’ergonomie des dispositifs, les usages et les formes de recours aux machines en sont conditionnés – ainsi des « smartwatches », par exemple, qui ont eu à se cantonner à des fonctions limitées, de l’ordre de l’alerte ou du signal.

L’ensemble de ces cadres qui instituent mon rapport au texte au cours de la rédaction a toutefois tendance à s’effacer sous mes yeux et, dans la pratique, à disparaître complètement de mon attention, la nature même d’un cadre étant de s’effacer devant son contenu qu’il désigne en même temps qu’il le conditionne (A. Béguin-Verbrugge, 2006).

D’où la nécessité de souligner, lors de l’analyse, le fait que chacun de ces cadres d’écriture affiche des marques (logotypes de logiciels propriétaires, « libres » ou « open source »), et qu’il s’agit là – pour la première fois de toute l’histoire de l’écriture – d’une intrusion explicite d’énonciateurs économiques (capitalistes ou alternatifs), au sein de nos pratiques intimes d’écriture quotidiennes.
