---
title: "Document"
date: "2023-03-30"
citation: false
---

Manuel Zacklad. Espace documentaire participatif et gouvernance. *Congress of the European Regional Science Association (47th Congress) and ASRDLF (Association de Science Régionale de Langue Française, 44th Congress) PARIS - August 29th - September 2nd, 2007.*, Aug 2007, Paris, France. ⟨sic_00202423⟩

Avant d’introduire les notions de Document et Dossier pour l’Action et d’Espace Documentaire Participatif, nous rappellerons quelques éléments de notre théorie du document (Zacklad 2006, 2007a). Celle-ci est elle-même inscrite dans notre vision de l’activité collective, la théorie des transactions coopératives (p. ex. Zacklad 2007e), qui prolonge et généralise les analyses interactionnistes de l’activité à l’ensemble des activités collectives et des artefacts en mesure de les médiatiser. Selon cette perspective, l’activité collective qui correspond au déroulement de transactions coopératives mettant en présence un réalisateur et un bénéficiaire (souvent dans une position au moins partiellement réciproque) est toujours médiatisée par des artefacts de nature diverse. Dans le cadre de conversations ou de débats, ces artefacts sont principalement de nature sémiotique. Nous considérons ainsi que les transactions à dominante communicationnelle donnent lieu à des productions ou, le plus souvent, des co-productions sémiotiques. Mais celles-ci n’en n’ont pas moins aussi un caractère tangible qui correspond au support matériel de la production sémiotique. Ce support se décline selon deux principales modalités : il peut être éphémère, quand il relève de la gestualité ou de l’oralité, ou il peut être pérenne quand il relève de la transcription ou de l’enregistrement. Sur cette base, en nous appuyant sur les fondamentaux de la documentologie (Briet 1951) mais également sur les travaux récents visant à les renouveler (Pédauque 2006), nous définissons le document comme une « production sémiotique transcrite ou enregistrée sur un support pérenne qui est équipée d’attributs spécifiques visant à faciliter les pratiques liées à son exploitation ultérieure dans le cadre de la préservation de transactions communicationnelles distribuées » (Zacklad 2007a). On établit ainsi une distinction entre l’activité générale de documentation, qui inclut la recherche ou la production d’informations et leur retranscription ou leur enregistrement, de l’activité plus spécifique de documentarisation, exploitation des supports facilitant l’organisation des « fragments de production sémiotique » qu’ils véhiculent. Le travail de documentarisation s’exerce selon les dimensions de l’articulation sémantique interne ou externe. La première vise à articuler entre eux les fragments de production sémiotique à l’intérieur d’un support unitaire. Dans le cas de l’écriture papier, il s’agit de jouer avec l’espace pour séparer les paragraphes, d’utiliser la typographie pour marquer les titres ou les sous-titres, etc. La seconde articule l’ensemble du support avec d’autres supports pour faciliter son classement et sa recherche. La logique est ici celle de l’organisation d’une collection et de la définition de critères de caractérisation des différents exemplaires qui la composent.
