---
title: "Editorialisation"
date: "2023-02-28"
---

## Définition 1

> Selon la définition restreinte, l’éditorialisation désigne l’ensemble des appareils techniques (le réseau, les serveurs, les plateformes, les CMS, les algorithmes des moteurs de recherche), des structures (l’hypertexte, le multimédia, les métadonnées) et des pratiques (l’annotation, les commentaires, les recommandations via les réseaux sociaux) permettant de produire et d’organiser un contenu sur le web9. En d’autres termes, l’éditorialisation est une instance de mise en forme et de structuration d’un contenu dans un environnement numérique. On pourrait dire, en ce sens, que l’éditorialisation est ce que devient l’édition sous l’influence des technologies numériques. 

- Vitali-Rosati, ["Qu'est-ce que l'éditorialisation"](http://sens-public.org/articles/1184/), 2016.


## Définition 2

> La deuxième définition est une extension de la première, en se basant sur l’idée que l’espace numérique implique une superposition et finalement, une fusion entre discours et réalité. J’expliquerai tout à l’heure cette idée plus en détail, mais pour le moment, limitons-nous à son principe général : dans un monde numérique connecté, exister signifie être éditorialisé. En effet, dans l’espace numérique, un objet doit être connecté et mis en relation avec les autres objets pour exister.

- Vitali-Rosati, ["Qu'est-ce que l'éditorialisation"](http://sens-public.org/articles/1184/), 2016.

## Définition 3

> L’éditorialisation désigne l’ensemble des dynamiques qui produisent et structurent l’espace numérique. Ces dynamiques sont les interactions des actions individuelles et collectives avec un environnement numérique particulier. 

- Vitali-Rosati, ["Qu'est-ce que l'éditorialisation"](http://sens-public.org/articles/1184/), 2016.

## Définition 4

> L’éditorialisation est l’ensemble des dynamiques qui constituent l’espace numérique et qui permettent à partir de cette constitution l’émergence du sens. Ces dynamiques sont le résultat de forces et d’actions différentes qui déterminent après-coup l’apparition et l’identification d’objets particuliers (personnes, communautés, algorithmes, plateformes…).

- Vitali-Rosati, ["Pour une pensée préhumaine"](http://sens-public.org/articles/1598/), 2021.
