---
title: "Enonciation éditoriale"
date: "2023-04-06"
citation: false
---


 Jeanneret Yves, Souchier Emmanuël. L'énonciation éditoriale dans les écrits d'écran. In: *Communication et langages*, n°145, 3ème trimestre 2005. L'empreinte de la technique dans le livre. pp. 3-15. DOI : https://doi.org/10.3406/colan.2005.3351

En somme, l'idée qu'il existe une « fonction éditoriale » sur Internet paraît faire son chemin, et avec elle une définition de cette fonction qui ne la réduit pas au métier d'wditeur, mais concerne un mode d'intervention spécifique sur l'ordre et l'image du texte. Il est d'autant plus important, dans ce contexte, de s'employer à poser vraiment cette question. En effet, la rhétorique antithétique (texte matériel / texte virtuel, pouvoir de l'éditeur / pouvoir du lecteur, intermédiation / autopublication, etc.), pour frivole qu'elle soit, habite profondément les analyses. Face à ces antithèses faciles, il faut s'appuyer sur deux exigences essentielles, qui sont celles de l'analyse sémiologique : d'une part, disposer d'un concept de l'« énonciation éditoriale », qui permette de saisir les transformations dont celle-ci fait l'objet au-delà d'un simple catalogue de produit ; d'autre part, repérer les niveaux d'intervention de l'écriture informatique dans ce processus. Ceci permet d'échapper à l'opposition entre le « texte virtuel » et le « texte réel », pour comprendre comment la sémiotisation du texte s'opère dans les processus matériels de sa mise en forme.  

En d'autres termes, une réflexion sur l'énonciation éditoriale doit aujourd'hui s'appuyer sur trois termes : l'« écriture », l'« écran » et les « pratiques ».

[...]

[L'énonciation éditoriale] désigne l'ensemble de ce qui contribue à la production matérielle des formes qui donnent au texte sa consistance, son « image de texte ». Il s'agit d'un processus social déterminé, qui demeure largement invisible du public, mais qui peut néanmoins être appréhendé à travers la marque qu'impriment les pratiques de métiers constitutives de l'élaboration, de la constitution ou de la circulation des textes. C'est pourquoi la notion d'énonciation ne renvoie pas ici à une métaphore linguistique ; elle suggère en revanche qu'en deça ou en amont de l'énonciation discursive d'un texte donné (l'oeuvre d'un auteur célèbre, le texte d'un règlement ou la mosaïque d'un journal par exemple) se situe une autre énonciation, d'un autre ordre, même si elle lui est intimement liée. Cet autre niveau d'énonciation définit les formes mêmes qui rendent le texte possible, qui lui permettent d'avoir une visibilité : ce qui le conduit à être hiérarchisé ou non, à conjuguer les discours de telle ou telle façon... Plus fondamentalement, l'énonciation éditoriale est ce par quoi le texte peut exister matériellement, socialement, culturellement... aux yeux du lecteur. En ce sens, on peut considérer l'énoniation comme la face sémiotique, matériellement préhensible, de la « structure structurée structurante » de l'*habitus* au sens où l'entendait Bourdieu (cf. *Le sens pratique*, Les Éditions de Minuit, 1980). Cet enjeu opère de façon puissante mais peu observée car il relève de ce que Perec appelait « l'infra-ordinaire », c'est-à-dire de ce qui disparaît à force d'évidence et auquel, de ce fait, on ne prête que peu d'attention. Ainsi en va-t-il de l'*habitus* et plus généralement des formes instituantes de l'information dans les processus de communication sur lesquelles repose la *doxa* contemporaine.

Selon [Wikipédia](https://fr.wikipedia.org/wiki/%C3%89nonciation_%C3%A9ditoriale) :

[L'énonciation éditoriale] s’articule autour de plusieurs points : d’abord, l’idée, reprise à Paul Valéry et Jacques Roubaud, que tout espace éditorial manifeste un sens formel : toute forme (typographie, paragraphes, couverture, etc.) signifie potentiellement quelque chose et travaille l’interprétation de l’œuvre. Ainsi, la matière littéraire (lexique, syntaxe, style de l’auteur) est en étroite relation avec la matière éditoriale, plastique, formelle. Cette interdépendance est le fruit d’une collaboration, plus ou moins explicite, entre différents acteurs qui s’emparent du régime de visibilité de l’œuvre au cours de son élaboration : l’éditeur, certes, mais aussi le maquettiste, le typographe, l’illustrateur, l’imprimeur, le relieur, le correcteur, jusqu’au distributeur et spécialiste du marketing. L’espace éditorial est pensé comme un champ de forces où s’articulent différentes « voix », différents gestes, qui peuvent être en opposition et s'organiser dans un réseau sémantique de questions : « la théorie de l’énonciation éditoriale consiste à essayer de comprendre qui parle, comment et à travers quoi dans un processus de communication. ».

À chaque étape, les acteurs de cet espace déposent quelque chose d’eux-mêmes ; ils manifestent leurs savoir-faire, leurs conceptions du monde et leurs valeurs, soit une énonciation. Si le lecteur ne la voit pas et ne la perçoit pas, il se trouve néanmoins orienté par cette configuration, à travers des parcours spécifiques, un choix typographique, la matière d’un dos, par exemple. En convoquant le concept d’infra-ordinaire de Georges Perec, E. Souchier montre le caractère paradoxal d’une telle entreprise : elle est d’autant plus efficace qu’elle disparaît, s’efface aux yeux du lecteur, qui se trouve ainsi orienté sans le savoir – un processus qui relève de la mémoire de l’oubli, concept forgé à partir d’un dialogue entre Perec, Merleau-Ponty et Lionel Naccache. Le chercheur désigne par-là un processus transitif, proche de l’habitus de Bourdieu, à partir duquel nous apprenons à être traversés par les formes éditoriales, sans buter sur chacune d’elles, pour nous orienter dans le monde, en mobilisant l’activité de lire-écrire. Si cet apprentissage est nécessaire, s’il assure l’efficience de l’entrée dans le monde des signes, il pose néanmoins problème d’un point de vue social et politique. C’est pourquoi l’étude des marques énonciatives se double d’une réflexion sur le pouvoir, qui se loge jusque dans ces petits espaces pour constituer un ordre ou un cadre instituant, impensé, dans lequel nous ne cessons pourtant de cheminer. 
