---
title: "L'architexte est un tombeau"
date: "2023-04-05"
categories: [journal]
draft: true
---


L'objectif de ce billet est de me laisser un rappel du piège dans lequel il est facile de tomber.
En résumé, il s'agit d'éviter l'écueil de réduire le monde à un seul prisme, ce qui est souvent le cas lorsqu'il s'agit de discuter de la sphère numérique qui est déjà complexe en elle-même.
Le terme de sphère numérique est employé dans ce billet pour désigner la totalité de l'infrastructure numérique, du *hardware* au *software*.
Cette réduction s'apparente à une isolation, par ce qu'elle vaut comme simplification de l'objet «numérique», et cela dans l'objectif d'en comprendre les arcanes.
Or à force de vouloir l'isoler -- pour mieux la déchiffrer -- cette sphère en vient à perdre toute connexion avec les autres sphères.
S'opère alors une transformation du numérique en un *cloud* inaccessible à qui n'est pas initié et entraîne vers des chemins de pensée sans issue.

Comme nous le développerons ensemble, ce replie de la sphère numérique sur elle-même entraîne dans l'absolu la fin de l'écriture (et pour ce qui m'intéresse la fin du chercheur), car dans cet espace où tout texte est structuré, il devient par la même occasion prédictible et prévisible (en somme il devient calculable), c'est-à-dire qu'il est entièrement objectivé.
Cet absolu du numérique en tant que sphère étanche ne laisse plus de place à la subjectivité et à l'imprévisible. 

Or, si la figure du chercheur est constitué d'écritures (voir mon billet précédent), ce paradigme de la sphère numérique absolument hermétique ouvre la possibilité de reconnaître un algorithme d'intelligence artificielle comme étant un chercheur.
Ce qui provoquerait la mort du chercheur tel qu'il est collectivement conçu.

## Le point de départ

Le postulat initial à partir duquel je construis mon anti-piège repose sur l'espace numérique comme strictement constitué d'écritures (numériques). 
Comprenons cet espace comme un système d'informations gigantesque dans lequel interviennent des émetteurs, des récepteurs et des technologies qui acheminent des messages contenant (ou non) des informations.
Tous ces échanges circulent sous la forme d'écriture.
Afin d'être compréhensibles et afin d'en réguler le trafic, quelle que soit la couche où elles se situent, ces écritures sont principalement structurées par ce que Jeanneret et Souchier (2019) nomment architexte.
L'architexte est défini comme suit : 

> [Lorsqu'elle est] spécifiquement appliquée aux médias informatisés, la notion d’*architexte* que nous convoquons n’est pas extérieure au texte mais lui est constitutive et opératoire.
> Nous partons du constat qu’« on ne peut produire un texte à l’écran sans outils d’écriture situés en amont » (Y. Jeanneret, E. Souchier, 1999).
> Suivant une étymologie grecque (*archè*, origine et commandement), nous proposons le terme *architexte* pour désigner « les outils qui permettent l’existence de l’écrit à l’écran et qui, non contents de représenter la structure du texte, en commandent l’exécution et la réalisation ».
>
> Glossaire.

Posée de cette manière, la sphère numérique n'est *a priori* pas choquante : elle ne sera pas considérée fausse, ni complètement vraie puisqu'elle est trop simplifiée.
Pourtant, elle recèle en son sein un inconscient culturel : la théorie de l'information telle qu'elle a été établie au tournant de la Seconde Guerre et sur laquelle repose toute l'infrastructure de la sphère numérique.
Ainsi, la description effectuée ci-dessus a un effet pernicieux puisqu'elle laisse ambigue la façon dont opère le numérique dans l'espace en s'appuyant sur un présupposé culturel, donc dans son rapport avec les autres sphères (sociales, politiques, etc.).
Nous y veviendrons plus longuement dans la première partie du billet.

La pratique de recherche en laboratoire consiste à isoler un paramètre de son environnement pour en tester les comportements en y appliquant différents *stimulus*.
L'objectif de ce travail est de comprendre le fonctionnement et le rôle dudit paramètre pour ensuite pouvoir l'observer dans son environnement initial et de par le comportement adopté en conditions «réelles», en déduire ces implications dans son écosystème.
Cette manière d'appréhender un objet est largement utilisée et réutilisée lorsqu'il s'agit du numérique : les spécialistes et moins spécialistes isolent le «numérique» 
En découle un traitement particulier, avec de nouvelles méthodes et méthodologies adaptées à ces écritures qui ont pour conséquence de justifier cette isolation et creuse encore le fossé entre l'espace et l'espace numérique.
Ce phénomène est d'autant plus amplifié depuis quelques années avec la mondialisation de divers artefacts tels que des algorithmes complexes, des objets de plus en plus connectés, un système monétaire «dématérialisé», etc.

L'hypothèse que je soutiens ici est que le fait de regarder l'objet numérique seulement à travers son propre prisme transforme l'architexte en tombeau.

Cependant, cette isolation n'est pas un total impensé : elle fait l'objet de multiples critiques depuis les années 1960 allant de la provocation de McLuhan jusqu'aux modélisations des écosystèmes de connaissances (Szoniecky). 



La réouverture de cette sphère sera réalisée depuis la théorie des médias, avec pour point de départ McLuhan, elle servira de socle théorique pour traverser cet écrit.

## La théorie de l'information

## L'inconscient culturel issu de la théorie de l'information

## La dimension matérielle de la théorie des médias

- McLuhan et Kittler : la provocation face au réductionnisme de la theorie de l'information
- Evocation de Debray et de la médiologie (retour de la critique vis-à-vis de la sémiologie)
  - proposition de faire des analyses de textes sans "nettoyage" : objectif est de montrer l'écriture réalisée par tous les partis

## Éditorialisation et matérialité 


C'est également dans ce sens là que théoriquement l'éditorialisation dépasse le cadre offert par la documentarisation. 
La première de ces théories traite de la manière dont se constitue l'espace dans son ensemble, alors que la seconde de la structuration et de la constitution d'un espace réduit : le document. 

Le document et son architexte signent l'arrêt de mort de l'intimité du chercheur, donc du chercheur puisque cet intime le constitue comme élément primaire situé à l'intérieur de l'intérieur de celui-ci.
Ces notions, initialement formulée pour décrypter et comprendre l'agencement des écritures numériques,  sont basées (culturellement) sur la théorie de l'information.
En ce sens, le système d'information numérique propose un modèle où chaque objet se retrouve structuré au sein d'une architec(x)ture définie.  

Le problème d'un tel système est que, dans l'absolu, si toutes les informations sont structurées, si l'ordre documentaire l'emporte sur l'entropie, le chercheur est voué à mourir et son intimité à disparaître. 
Toutes les informations deviennent prévisibles, ainsi, il devient possible d'anticiper les meilleurs parcours/formations à suivre, les personnes que l'on doit rencontrer, les articles à écrire (quels sujets, dans quelles revues, etc.).
Un algorithme tel que ChatGPT peut dès lors devenir un chercheur -- sans intime.  

En un sens, c'est ce qu'essaye de dépasser l'éditorialisation à partir de 2021. L'éditorialisation est définie selon un ensemble de conjonctures médiatrices qui produisent les choses, jusqu'à l'espace que nous occupons : un ensemble de médiations s'incarnent dans une chose et lui confère du sens. L'éditorialisation échappe au vase clos de l'utopie numérique et à son propre tombeau en acceptant en son sein une certaine forme d'entropie qui jusque-là aura été absente (nous y reviendrons). L'éditorialisation n'est plus anthropocentrée ni centrée sur le numérique, elle accepte dorénavant de nouvelles formes et modèles. 

Du côté de la théorie des médias, McLuhan et Kittler ont anticipé cette mort inévitable (ajouter le questionnement de Kittler ?). Il s'agissait d'ailleurs de leur cheval de bataille exprimé sous la forme de provocations (Le medium est le message ou encore le logiciel n'existe pas). 

D'ailleurs, une bonne partie de ce discours est tenu face au paradigme dominant sur lequel repose toute notre infrastructure numérique : la théorie de l'information et la gestion de l'entropie écrit par Claude Shannon en 1948.
Cette équation si célèbre permet de définir mathématiquement l'entropie en tant que valeur statistique dans un système d'informations : à partir de cette objectivation du phénomène d'entropie, il devient possible et nécessaire de la juguler et de la réguler pour la minimiser et la maintenir à un niveau déterminé : c'est un processus d'optimisation du système d'informations. Ainsi on maîtrise le niveau d'entropie d'un système donné tel un phénomène variable que l'on peut ajuster selon les besoins.
Dans l'*oeuvre ouverte*, Umberto Eco met en balance ces deux phénomènes (mathématiques) que sont l'ordre et l'entropie. 
C'est la structuration rigoureuse des messages qui permet donc de réduire le facteur entropique.
Un système d'informations se construit sur cette balance entre l'ordre et l'entropie. 
L'ordre se traduit par réduction de la quantité d'informations du système afin qu'elles soient compréhensibles tout en acceptant certains effets comme une redondance presque excessive.
Il s'agit du pendant de l'entropie, l'excès d'ordre entraîne une répétition de l'information qui n'en devient plus une mais seulement du bruit ou un message qui tend à devenir un cliché.
C'est l'association de cette redondance avec un nettoyage/réduction du bruit dans un système d'informations qui jugule l'entropie (et permet d'en ajuster le niveau).

Revenons-en au tombeau qui nous intéresse. Il s'agit en fait d'une abstraction réalisée pour expliquer les phénomènes de l'espace numérique en le réduisant à sa seule sphère isolée du reste du monde -- comme un laboratoire --, ce qui a pour conséquence de confiner les notions qui en découlent à l'intérieur de celle bulle (architexte numérique, certains degrés de l'éditorialisation, la documentarisation et le document). 

NB : Étonnament la notion d'énonciation éditoriale opère des vas-et-viens entre les sphères, nous y reviendrons.

De fait ces notions ont un point commun : elles ne traitent que trop souvent de la question de l'espace numérique que comme isolé. 
Il en devient un système d'informations quasiment hermétique car on ne pense plus en dehors de cette sphère là. 
Et même pour aller un peu plus loin, en dehors des couches logicielle et réseau (si on reprend le modèle sémiologique de E. Souchier), les couches système et matérielle sont énoncées mais mises à l'écart : elles sont réduites au rang de porte d'accès au système d'information numérique.  

Ce système considère l'écriture comme humaine et machinique et n'agissant qu'en son sein. C'est précisément ce point de vue qui ne peut plus être soutenu : parce que dans l'**absolu** (et absurde), si toutes cette construction est en vase clos, chacune des productions sémiotiques y sera structurée transformant alors l'espace numérique en document géant. *In fine*, chaque information sera prédictible et prévisible : nous aurions affaire à un espace complètement objectivé et calculable où le subjectif et l'imprévisible n'auraient plus leur place.
Selon cette vision du numérique, rien n'empêche alors de définir un algorithme en tant que chercheur s'insérant littéralement dans un réseau. 

Les quatre couches sémiotiques de Souchier en sont également l'argument : à l'endroit où un modèle réduit une vision du monde, il en propose également une simplification qui oublie les autres plans sémiotiques potentiels de construction du sens.

L'éditorialisation telle qu'elle est conçue dans les travaux de Bachimont en suit également les traces et cela jusqu'aux intuitions de Louise Merzeau (2013) avec l'éditorialisation collaborative d'un événement. 
Toutefois il faudra encore attendre plusieurs années que Vitali-Rosati prenne position du côté des *posthuman studies* afin de formaliser et d'expliciter une nouvelle posture qui réouvre l'espace numérique. 
Il ne s'agit pas simplement d'un léger pas sur le côté et d'accorder une propriété de perméabilité à la sphère numérique.
L'ancrage de l'éditorialisation dans les *posthuman studies* (et dans une partie de l'héritage de McLuhan et Kittler) entraîne un éclatement total de cette image rémanente d'une sphère numérique indépendante et la réintègre malgré elle dans les autres couches sémiotiques qui composent notre espace.
Le medium, support de l'information, n'est à ce stade plus le message comme pouvait l'affirmer McLuhan. 
Comme nous l'avons évoqué précédemment, l'éditorialisation désigne l'ensemble des conjonctures médiatrices (des médiations) qui à un instant donné fait émerger la matérialité du message et de son medium support. 
Cette modélisation complexe du monde accepte en son sein des dimensions subjectives, affectives, destructurées.


C'est une ouverture qu'on retrouve aussi dans l'énonciation éditoriale (Souchier). Le jeu de *lettrure* provoque des allers-retours entre les différents acteurs de la chaîne éditoriale (jusqu'aux lecteurs) et crée des percées dans un espace numérique intermédiaire agissant dans la sphère sociale. Le geste d'énonciation est une action de prise de pouvoir (une autorité) agissante dans l'espace social, à travers et en dehors de l'espace numérique.




