---
title: "Le traitement de texte est une souffrance"
date: 04/28/2023
categories: [these, journal]
draft: true
---

[Pour la présentation lors du séminaire de R. A.]

#déclinaisons

Le fait n'est pas nouveau : l'usage d'un logiciel de traitement de texte pour éditer un texte, qu'il s'agisse d'une revue, d'un ouvrage, d'un billet de blog, etc., est réellement une souffrance. Le terme de traitement est d'ailleurs bien choisi, il emporte avec lui le poison de sa mauvaise utilisation. C'est un mal face auquel seule la patience peut lutter.

Si l'écriture permet l'émergence de la pensée, alors son traitement est la cause de sa déchéance. Il incombe alors au reste de la chaîne éditoriale de prendre soin (on peut dès lors s'en référer aux deux sens portés par le terme, *to cure* et *to care*) du texte et de faire un retour en arrière, d'effacer tout balisage malin et de restaurer un état supposé initial du texte pour le travailler.

L'auteur qui rencontre les événements qui suivent l'étape d'écriture dans la chaîne éditoriale sait de quoi il retourne. 

Les outils de traitement de texte proposent à tout le monde de (mal) faire le travail typographique dans un texte.
Les auteurs n'ent ont, pour la plupart, aucune conscience : on le remarque surtout dans les tapuscrits qui ne sont pas bien structurés, où les fontes changent en fonction de ce que l'auteur pense vouloir dire, où des emphases sont employées pour structurer du contenu (un niveau de titre 3 ou 4 par exemple), et j'en passe.

Pourtant, la plupart des maisons d'édition ne remettent pas ce premier maillon en cause et les graphistes continuent de ré-intégrer les textes bruts dans leur logiciel de PAO pour ensuite restructurer le texte convenablement (en vue de correspondre à la maquette de l'artefact souhaité). 

Sans refaire le détail de toutes les horreurs engendrées par ce fonctionnement cassé, il convient de noter que cette chaîne est non productive car elle repose sur le principe de la **panne**. 

D'où sort cette panne ? Tout simplement du jargon de technicien.

Très grossièrement le rôle d'un technicien consiste à prendre soin d'une machine. Ce rôle peut se décliner en trois parties : 

- sa mise en oeuvre ;
- une maintenance préventive (des routines pour vérifier que tous les indicateurs présentent des indices de bon fonctionnement) ;
- la maintenance corrective (réparer les pannes). 

On peut donc reformuler :  la mise en oeuvre de la chaîne éditoriale basée sur un traitement de texte mal utilisé repose sur une partielle maintenance corrective. C'est un principe récurrent qu'on remarque surtout lors de situations de *crise*.
Lorsque le fonctionnement n'est pas nominal mais que tous les acteurs d'une chaîne sont au courant d'une panne, et de son comportement, il devient possible d'adapter le protocole de fonctionnement sur le comportement de la panne. Cela demande une surveillance supplémentaire mais offre l'avantage de continuer à fonctionner (parfois sur un mode plus ou moins dégradé). 

Cette situation est normalement temporaire ! Dès que la crise est passée, l'objectif reste d'effectuer une maintenance corrective complète pour retrouver un fonctionnement nominal. 

Or, le problème d'une chaîne éditoriale basée sur un logiciel de traitement de texte est quelle repose nominalement sur l'intégration de balises malignes sans aucune signification pour lesquelles il faut ensuite opérer des suppressions (automatiquement et manuellement) -- est-ce qu'on s'accorde sur le terme ablation ? -- avant de pouvoir réaliser le travail d'édition.

<\!-- Avouons entre nous que c'est le comble pour une économie néolibérale ! -->

Pour clore ce billet, on peut résumer cette chaîne par le fait que le traitement d'un texte requiert de traiter son traitement.