---
title: "La manifestation de l'intimité du chercheur à travers les écritures numériques savantes"
subtitle: "Cas des publications scientifiques"
date: "2023-03-14"
categories: [news, these]
---

Ce document est une ébauche de mon sujet de thèse, c'est encore une version de travail. 

## Problématique

Comment se manifeste l'intimité du chercheur dans les écritures savantes, et plus précisément dans les publications scientifiques ?

## Hypothèse 

L’hypothèse émise est celle d’une intimité produite par l’écriture. C’est-à-dire que le chercheur·e est le résultat des dynamiques d’écriture et de publication auxquelles il se mêle. Il faut entendre par dynamiques un agencement complexe d’actions, d’événements, de liens entre des individus, des collectivités, des technologies, une structure composant la sphère sociale, politique et technologique dans laquelle s’insère la figure du chercheur·e. Ce que nous chercherons à démontrer dans cette thèse est que cet intime, cette incrustation des chercheur·e·s dans les dynamiques mentionnées, est une production contingentée à l’acte d’écriture numérique.

## Présentation du sujet

À travers cette recherche, je souhaite étudier la façon dont se construit et se manifeste l'intimité du chercheur dans ses écritures numériques savantes. Il ne s'agit pas de se focaliser sur des individus particuliers, mais sur le chercheur, en tant que figure sociale spécialiste rattachée à un organisme ou à une institution publique, au 21e siècle en occident (précise-t-on ici les Lettres et SHS pour mieux cibler l'étude ?). 
Afin de traiter cette problématique, je souhaite faire cette recherche dans l'axe de la théorie des médias qui apparaît dans les années 1960 avec les textes de Marshall McLuhan et connaît depuis l'apparition de différents courants de pensée.

Le postulat initial sur lequel je m'appuie est celui de la figure du chercheur comme constituée d'écritures puisque le parcours de recherche en est jalonné de toutes sortes : des ensembles de textes d'abord sous forme de mémoire et de thèse, des diplômes ou des qualifications, puis des articles et des monographies, des demandes de subvention, des carnets, des conférences, un *curriculum vitae*, des lettres, des compte-rendus, des observations, des découvertes, des analyses, des *posts* sur les réseaux sociaux, des courriels, etc. Cette figure sociale est un *corps de textes* mû par l'écriture et possède son noyau : l'intime. Plusieurs types d'écritures savantes numériques viennent d'être nommées, elles constituent cependant un champ très vaste et plusieurs objets de recherche. Les écritures savantes représentent l'ensemble des écritures qui peuvent être rattachées à une figure sociale (du savant). Parmi toutes les écritures savantes se trouvent les publications scientifiques. Ces publications sont un sous-ensemble sur lequel nous nous focaliserons pour notre recherche, et nous exclurons les autres. 

L'intime, du latin *intimus*, est le superlatif de l'intérieur, noyau qui se trouve aux tréfonds de l'être et participe à sa constitution. Cette notion apparaît pour la première fois en l'an 397 dans les écrits de Saint-Augustin [-@augustin_confessions_1993] et s'enrichit depuis d'une multitude d'acceptions [@montemont_dans_2009]. Ainsi, l'intime désigne tour à tour des espaces (tel que le boudoir ou la chambre), des informations, des relations, des correspondances, des carnets, des données, sans jamais trouver de forme réellement figée. Finalement, ce concept désigne des rapports et des liens à soi et à l'autre [@jullien_intime_2013] rendus accessibles par le truchement d'objets ou d'espaces. Sans entrer dans le champ de la psychanalyse, l'intime se rapproche de ce qui est nommé inconscient bien des siècles plus tard. Dans le cadre de cette thèse, l'intime sera défini plus largement et considéré comme un ensemble d'expériences qu'un individu juge subjectivement comme inaliénable. L'intime appartient à l'individu, mais cette appartenance n'est pas à saisir sous le sens de la propriété. L'intime lui appartient, car l'intime **est** l'individu, l'appartenance est dans ce cas un abus de langage. Ainsi, il semble incohérent d'associer l'intime à la propriété privée, débat qui fait couler tant d'encre, notamment depuis l'intrusion des questions juridiques en matière de distinction entre ce qui relève de la vie privée ou de la place publique et, plus tard, de la controverse sur les données personnelles (*privacy*) datant du début des années 2000.  
Un paradoxe réside à cet endroit et participe à créer une certaine opacité d'une intimité qui subsiste à la fois dans un lien et dans des supports.
Selon la définition précédente, c'est l'expérience, à travers une médiation, qui est intime. Ainsi, les indices qui peuvent en résulter seraient des **traces** de l'intime. Ces indices ou traces sont des marqueurs d'une intimité-déjà-passée (qui pourrait être réactivée à travers la médiation, par exemple par la relecture d'une lettre) et ce sont eux qui peuvent s'échapper de la sphère de l'intime jusqu'à la sphère publique. Pourtant, sans ce support médiatique, l'intime n'existe pas. Ainsi présenté, ce paradoxe fait apparemment coexister (en friction) deux intimités : l'une est subjective et l'autre est indicielle (et matérielle). Néanmoins, ces deux visions ne sont pas dans une opposition absolue. La définition précédemment énoncée dépend d'un contexte et donc d'un système d'informations très particulier, car étanche et inviolable : une subjectivité détermine si un rapport appartient à ce champ d'expériences intimes ou non, donc si la médiation à soi-même ou à l'autre y est incluse ou non. Dans ce contexte, les deux intimités mentionnées deviennent complémentaires et se suivent temporellement dans le système d'informations clos, c'est-à-dire que l'expérience est conditionnée par la matérialité. Les traces font partie intégrante de l'intime et permettent de réactiver l'expérience lors de chaque réactivation de celles-ci. Or, si une trace échappe à ce système d'informations, si elle est publiée, elle ne peut plus appartenir à ce champ intime : sa valeur indicielle permet cependant à une extériorité de connaître l'existence d'une intimité-déjà-passée, mais elle tait l'expérience en elle-même puisque, nous l'avons vu, elle *est* l'individu, inviolable. L'ensemble qu'est l'intime intègre en définitive l'expérience et son support, mais si le support en est détaché, il n'est plus intime, seulement un fragment l'évoquant.

Note : Ce bref découpage du paradoxe sert principalement à dissocier l'intime dans son système clos de celui qui en est à l'extérieur, et d'expliquer pourquoi il n'est plus intime une fois dehors. En se basant sur la pensée de McLuhan, l'expérience et le medium ne serait plus à distinguer : le medium deviendrait l'intime dans son intégralité (l'intime est une médiation s'inscrivant dans un système d'informations unique et déterminé). Ce point constituera un développement possible de l'intime, et sera traité dans un autre papier.

Continuons avec l'exemple d'une correspondance intime. Conformément à ce qui vient d'être énoncé, l'environnement intime est déterminé selon deux paramètres : les protagonistes et un medium. Pour l'exemple, les protagonistes sont au nombre de deux et le medium est composé d'une correspondance au format papier. Les actions d'écrire et de lire sont les médiations et participent de l'expérience intime de cette relation épistolaire. Les événements ainsi posés ne laissent aucun doute quant à l'existence de cette intimité grâce à la lettre même. Si cette relation se déroulait par téléphone ou courriel, sa nature en changerait ou s'il n'y avait rien de cela, elle n'existerait peut-être pas. L'écriture d'une lettre, ou la lecture d'une réponse, sont les moments de connexion à l'autre, un lien s'établit même s'il est différé dans le temps. D'ailleurs, cette connexion ne s'établit pas seulement à la première lecture puisqu'une relecture peut permettre de réactiver ce lien, donc l'expérience.
En revanche, si cette lettre est **publiée** dans un journal, elle témoignera d'une intimité passée, mais n'en dévoilera seulement que des indices plus ou moins flagrants : effet que certains spécialistes nomment extimisation. Cette publication n'est plus qu'un indice du lien existant entre les deux correspondants et ne permet pas à un lecteur tiers de vivre l'expérience de ce lien : nous ne sommes plus dans le champ intime.

Cette perception de l'intime relève en conséquence d'une médiation particulière et concerne le rapport d'un individu à lui-même ou à l'autre. L'intimité, lorsqu'elle est renvoyée à la figure du chercheur, pourrait être rattachée à l'écriture, ce qui constitue notre postulat initial. Si le chercheur est constitué par des écritures, celles-ci doivent également avoir un rapport avec le noyau à *l'intérieur de l'intérieur* de cette entité. Si nous suivions l'héritage cartésien traditionnel, et le célèbre *cogito ergo sum*, l'hypothèse que nous pourrions envisager pour répondre à notre problématique serait celle du sujet penseur, dont l'intimité permettrait de produire l'écriture. Il y aurait une intimité détachée des écritures, pré-existante, à partir de laquelle seraient agrégées des écritures pour former l'image du chercheur.
La position que je souhaite tenir est tout à fait inverse, non anthropocentrée, et vient plutôt s'inscrire dans la pensée préhumaine, courant posthumain s'insérant dans la théorie des médias [@vitali-rosati_pour_2021] : celle où l'écriture précèderait l'intime. Dès lors, le chercheur serait le résultat de dynamiques d'écritures et de publications auxquelles il est soumis, et son intimité résulterait de ce processus. Ces dynamiques (que nous pourrions nommer conjonctures médiatrices [@vitali-rosati_media_2019]) sont un ensemble de médiations rattachées à différentes sphères politiques, techniques et sociales. Elles définissent le milieu au sein duquel évolue le chercheur. En somme, l'intimité du chercheur, et par extension le chercheur lui-même, n'existe que parce qu'un milieu particulier la fabrique. Ainsi, la problématique formulée initialement peut être renversée : il ne s'agit plus de questionner l'expression de l'intimité du chercheur dans les écritures savantes, mais plutôt d'essayer de savoir quel est l'impact du fait numérique sur l'intimité du chercheur.

Toutefois, il est légitime de se poser la question de l'étude de l'intime : comment faire ? L'objectif de cette recherche n'est pas de mettre en avant une individualité particulière, ou de se focaliser sur la dimension subjective de l'intime (par définition inaccessible). Cette aspect de l'intime serait, a priori, impossible à étudier. Pour autant, nous avons évoqué les traces de l'intime, celles qui persistent dans l'espace public et à partir desquelles nous pourrions mener notre recherche.

Aussi, l'étude de ces médiations intimes sera réalisée depuis les traces intimes et le prisme de la théorie des médias. La genèse de cette théorie remonte aux années 1960 si nous laissons de côté les essais philosophiques qui traitent partiellement de ce sujet (nous pouvons remonter jusqu'à Platon). À cette période, Marshal McLuhan, considéré unanimement comme le père des *media studies*, publie la *Galaxie Gutemberg* [-@mcluhan_galaxie_2017] et *Pour Comprendre les médias* [-@mcluhan_pour_1977], deux textes références en la matière. La célèbre provocation "The medium is the message" se positionne à l'opposé de la pensée dominante de cette époque qui est issue de la cybernétique et de la théorie de l'information développée dans les années 1950 (entre autre par Shannon, Wiener, Turing [@shannon_mathematical_1948]) , celle où le medium n'est rien d'autre qu'un support de l'information, il n'entre pas dans l'équation du sens de cette dernière. Au-delà d'une simple provocation, la pensée de McLuhan fait école [de Toronto] et continuera à frayer son chemin jusqu'en Europe. 

Dans l'Allemagne des années 1970, Friedrich Kittler [-@kittler_gramophone_2018] traite, à la suite de McLuhan, de la question de l'écriture et du medium qu'est l'ordinateur (sujet pas tant abordé par McLuhan). En France, les sciences de l'information et de la communication arrivent tardivement, il faut attendre 1975 pour que cette (inter)discipline naisse officiellement. Quelques années plus tard, en 1979, Régis Debray emploie pour la première fois le terme de *médiologie* dans son ouvrage *Le pouvoir intellectuel en France*, cependant il faudra attendre la publication du *Cours de médiologie générale* en 1991 pour poser les fondations théoriques de ce champ d'étude, courant qui se distingue des autres écoles de pensée de la théorie des médias. Par la suite, d'autres courants voient le jour à partir des années 1990 comme l'intermédialité [@tadier__2021]  (école montréalaise dont l'origine se trouve dans les années 1960) ou encore la naissance de concepts qui s'inscrivent dans des courants plus génériques, par exemple l'énonciation éditoriale [@souchier_image_1998], la (re)documentarisation [@zacklad_design_2019] et l'éditorialisation [@merzeau_editorialisation_2013] dans le courant francophone ou encore la *remediation* [@bolter_remediation_1998] pour le courant anglophone. 

La théorie des médias fait apparaitre deux enjeux autour de notre problématique : celui, tout d'abord, de l'apparition de l'intime au croisement de l'écriture numérique (technique) et du monde social, politique et culturel dans lequel évolue le chercheur, puis, celui de la transmission, donc de la nécessité de faire trace et mémoire. 

À l'endroit de l'écriture numérique, l'enjeu social, politique et culturel touche plus que toutes les autres la dimension de publication de la recherche. 
Le modèle actuel de publication scientifique est hérité d'une tradition d'un peu plus de trois siècles : il faut remonter à la fin du 17^e^ et début du 18^e^ siècle pour observer la naissance des premières revues savantes [@vittu_trois_2019]. Lorsque le système postal n'est plus réservé à la noblesse, les savants l'emploient pour entretenir des correspondances entre eux. Le papier est cher et précieux, les échanges sont relativement courts (quelques pages tout au plus) et ressemblent vaguement à une forme du type "article". En 1665, la première revue (Le Journal des Savants) fonctionne sur le principe d'un recueil de lettres qui puisse être rendu accessible à tous (publié) et se dégager ainsi du silo de la correspondance. Le fonctionnement a depuis bien évolué, les outils techniques se globalisent et les protocoles de publications scientifiques ont bien changé.
La transition à la fin du 20^e^ siècle au numérique ubiquitaire déplace le paradigme de l'imprimerie traditionnelle vers celui de l'écriture numérique. Cette écriture se voit dotée de nouvelles caractéristiques : elle ne concerne plus seulement l'inscription de signes sur un support, mais toutes les captations qui entrent dans le champ du numérique, puis elle devient computable. S'opère alors une transformation des espaces et des architectures à laquelle le modèle de publication scientifique n'échappe pas [@vitali-rosati_quest-ce_2020].

La chaîne de publication scientifique mobilise différents acteurs : des éditeurs, des relecteurs, des développeurs Web, des outils, etc. 
Dès lors, l'écriture (numérique) savante se voit altérée par les modifications, les conversions ou les transformations. Ce fait n'est pas nouveau et ne date pas de l'ère numérique. Cependant, une différence notable apparaît : les écritures numériques ne sont pas le fait des êtres humains, tout un ensemble de robots, de logiciels, et d'algorithmes lisent, encodent et écrivent des textes qu'aucun humain ne lit. Les textes écrits par des humains sur un support numérique ne sont que des représentations de ce que cet ensemble numérique écrit, manipule ou transforme [@kittler_mode_2015]. Dans le cadre d'une publication, un fichier rédigé sur un ordinateur (en local) transite ensuite par plusieurs terminaux, sous différents systèmes d'exploitation et autres technologies, puis est annoté et corrigé par plusieurs mains avant d'être validé pour publication ; ainsi les acteurs de cette chaîne éditoriale (humains et numériques) participent à l'élaboration de cette écriture savante. Il ne s'agit plus d'un système où la seule existence du chercheur repose sur la reconnaissance par les pairs, mais repose également sur toute une infrastructure sociale et technique qui participe littéralement à l'écriture du texte.
Nous pourrions à cet endroit émettre une nouvelle hypothèse d'une construction collective de l'intimité du chercheur (agents humains + agents numériques qui participent à l'écriture).

Qu'advient-il de cette intimité une fois qu'elle est publiée ? Jusqu'à présent, l'intérêt porté à la problématique était concentré sur l'écriture et le processus de publication, et soulève la possibilité que l'intimité produite par les écritures savantes ne soit pas individuelle, mais collective.
Une fois relâchée dans l'espace public, l'écriture se détache de l'intimité qu'elle a initiée et devient un ensemble de traces dont la fonction indicielle dévoile un fragment de cette dernière et participe à créer la représentation abstraite d'un chercheur dans l'écosystème savant. Nous venons d'entrevoir le fait que les écritures numériques façonnent les architectures de nos espaces, n'en serait-il pas de même pour les chercheurs ? Est-ce que ces écritures numériques, ces traces intimes publiées, ne participeraient-elles pas à façonner ces tréfonds de la figure sociale qu'est le chercheur ?
Cette question nous écarte de l'intimité vécue à la première personne (donc de l'expérience) que nous avons vu jusqu'à maintenant et nous renvoie à l'étymologie du superlatif de l'intérieur. Il ne s'agit plus d'essayer de contenir une expérience et sa médiation, mais de représenter depuis l'espace public, l'intérieur de l'intérieur de notre figure sociale à partir des traces qui subsistent d'elle. Nous ne sommes plus dans un système d'informations fermé, mais dans un système public et accessible. Il ne s'agit plus de l'intime, mais d'une image de l'intimité renvoyée par les traces intimes que l'on peut (pour l'instant) nommer représentation. Pour le reformuler, il s'agit de représenter la figure du chercheur depuis ses écritures laissées dans l'espace public. L'enjeu est une recollection des traces, de la mémoire, par des agents externes, afin de reconstituer à travers les indices laissés une représentation de cette figure sociale. 
De la même manière que les chercheurs qui, dès l'origine, sont institués par les pairs, la représentation collective qui en persiste dans la sphère sociale est celle constituée par une communauté. L'hypothèse émise ici est que la réactivation des traces intimes d'une œuvre -- citation dans d'autres écrits, dans les références bibliographiques ou dans les textes, réédition ou recherches menées sur ses écrits -- par des extériorités permet de faire exister le chercheur dans son monde social. L'intimité du chercheur ferait ainsi l'objet d'un double mouvement. Nous retrouvons d'abord l'intimité telle qu'une expérience médiée au sein d'un système d'informations inviolable et vécu à la première personne, puis vient une intimité mémorielle dont l'ensemble des indices qui sont collectés par les autres, extérieurs au système d'informations précédent, forment une représentation de l'intime, et par extension du chercheur, dans la sphère sociale de la recherche. L'hypothèse précédente pourrait être complétée par le fait que, dans sa relation au lectorat, le mode d'existence du chercheur (et la représentation de son intimité) continue à fluctuer dans le temps sous sa forme mémorielle.  

Un des grands enjeux de la recherche est de faire trace. Au-delà des enjeux de publication, les écrits scientifiques servent de socle pour les générations à venir, nous amenant ainsi à considérer la question de la transmission, que nous pourrions formuler en deux sous-questions : 

- Comment fluctue cette représentation de l'intime (les rééditions, modifications de l'architexte, etc.) ?
- Quelle est le rôle de cette représentation de l'intime dans la transmission des savoirs ?

Note : Peut-être que cette dernière question de recherche pourrait être une ouverture ou d'un projet ultérieur, elle sort un peu des bornes de la problématique.

En conclusion, l'articulation théorique autour de la théorie des médias permettra dans un premier temps de définir ce qu'est l'intimité du chercheur et en quoi elle diffère des acceptions les plus communes. Ce premier aspect de la recherche sous-entend le dépassement de la fonction "support" que peut tenir l'écosystème numérique (*hardware* + *software* + espace public) pour devenir une dynamique participante de la fabrication de l'intime.
Ensuite, un second temps sera dédié à disséquer cette intimité nouvelle pour en découvrir les différentes composantes et leur participation à cette construction. Lors de cette étape, l'objectif sera de retracer les actions de l'ensemble des acteurs agissant sur le processus d'écriture des publications scientifique afin de déterminer leurs possibles contributions sur la publication (et sur l'intimité qui en résulte). Enfin, une dernière partie sera consacrée à la recollection des traces afin d'observer de quelle manière circulent les traces et s'il est possible de faire émerger une représentation de(s) l'intimité(s) concerné(s).


## Notes à développer 

### Proposition pour la revue de littérature

L'intimité constituée d'écriture : 

- Réalisation d'une cartographie des différents courants de la théorie des médias à partir des bibliographies d'un ensemble de textes majeurs dans le domaine (si les bibliographies existent, ce qui n'est pas sûr pour tous les ouvrages / articles). Justifier l'approche théorie des médias et la définition de l'intime qui en découle.


### Propositions de terrains

Intimité collective : 

- Études comparatives de deux chaînes de publication de revues : observation des modifications opérées par les différents maillons (humains et technologiques) sur un numéro complet ? (exemple avec la revue Humanités Numériques et SFSIC ou Hybrid ? voir les modifications sémantiques des sources + analyse des publications finales textes + supports + architextes de Souchier, etc.)
    - Des analyses des chaînes de publications côté humain existent déjà, mais qu'en est-il de l'analyse de la participation technologique à la production scientifique ?
    - Cette proposition prend en considération les dimensions software et hardware, on peut envisager de faire des entretiens avec les acteurs concernés pour connaitre leur environnement de travail (les versions des logiciels, les différentes facettes de leur machine, claviers, souris, webcam, les logiciels frequemment utilisés, les modes de pensée WYSIWYG ou WYSIWYM)
        - À cette dernière proposition on peut ensuite aller chercher les documentations techniques de l'ensemble des outils utilisés, comprendre les schémas de construction, les enjeux qui étaient derrière (exemple avec le clavier : utilisation d'un clavier Qwerty US pour la disposition des 104 touches, et l'installation d'un layout Qwerty-Lafayette pour avoir les accents et les espaces insécables sous la main. Le rétroéclairage ou non, les touches mécaniques ou non, etc ... Qu'est-ce que ceci raconte du procédé d'écriture ?)
        - Pour mieux rendre compte de cette proposition, je peux commencer par faire une fiche exemple avec ma configuration ?


Mémoire de l'intime et transmission : 

- Œuvre de Louise Merzeau.
    - État des archives de ces textes
    - Comment former une collection
    - Processus de sélection des textes
    - Processus d'écriture (technique et humain)
    - Choix des infrastructures partenaires (quels sont leurs impacts ?)
    - Choix de publication (pourquoi et qu'est-ce qu'ils donnent comme sens ?)
        - supports
        - formats
        - techniques
    - Diffusion et communication (puis, quelles sont les réactions ?)